// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBook(arg1) {
  return window['go']['main']['App']['CreateBook'](arg1);
}

export function GetAllBooks() {
  return window['go']['main']['App']['GetAllBooks']();
}
